"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gpsData(object):
    __slots__ = ["timestamp", "lat", "latDir", "lon", "lonDir", "alt", "utm_x", "utm_y"]

    def __init__(self):
        self.timestamp = 0
        self.lat = 0.0
        self.latDir = ""
        self.lon = 0.0
        self.lonDir = ""
        self.alt = 0.0
        self.utm_x = 0.0
        self.utm_y = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(gpsData._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qf", self.timestamp, self.lat))
        __latDir_encoded = self.latDir.encode('utf-8')
        buf.write(struct.pack('>I', len(__latDir_encoded)+1))
        buf.write(__latDir_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">f", self.lon))
        __lonDir_encoded = self.lonDir.encode('utf-8')
        buf.write(struct.pack('>I', len(__lonDir_encoded)+1))
        buf.write(__lonDir_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">fff", self.alt, self.utm_x, self.utm_y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gpsData._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gpsData._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gpsData()
        self.timestamp, self.lat = struct.unpack(">qf", buf.read(12))
        __latDir_len = struct.unpack('>I', buf.read(4))[0]
        self.latDir = buf.read(__latDir_len)[:-1].decode('utf-8', 'replace')
        self.lon = struct.unpack(">f", buf.read(4))[0]
        __lonDir_len = struct.unpack('>I', buf.read(4))[0]
        self.lonDir = buf.read(__lonDir_len)[:-1].decode('utf-8', 'replace')
        self.alt, self.utm_x, self.utm_y = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gpsData in parents: return 0
        tmphash = (0x68be2ac79e87db4d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gpsData._packed_fingerprint is None:
            gpsData._packed_fingerprint = struct.pack(">Q", gpsData._get_hash_recursive([]))
        return gpsData._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

