/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class imuData implements lcm.lcm.LCMEncodable
{
    public float MagX;
 
    public imuData()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x7c6e135c77fc36ceL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.imuData.class))
            return 0L;
 
        classes.add(exlcm.imuData.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.MagX); 
 
    }
 
    public imuData(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public imuData(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.imuData _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.imuData o = new exlcm.imuData();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.MagX = ins.readFloat();
 
    }
 
    public exlcm.imuData copy()
    {
        exlcm.imuData outobj = new exlcm.imuData();
        outobj.MagX = this.MagX;
 
        return outobj;
    }
 
}

