"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class imuData(object):
    __slots__ = ["MagX"]

    def __init__(self):
        self.MagX = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(imuData._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.MagX))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imuData._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imuData._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = imuData()
        self.MagX = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if imuData in parents: return 0
        tmphash = (0x7c6e135c77fc36ce) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if imuData._packed_fingerprint is None:
            imuData._packed_fingerprint = struct.pack(">Q", imuData._get_hash_recursive([]))
        return imuData._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

